import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { Navigation } from "@/components/Navigation";
import { CssBaseline } from "@mui/material";
import { ThemeRegistry } from "@/lib/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <ThemeRegistry>
        <CssBaseline />
        <html lang="en">
          <body className={inter.className}>
            {children}
            <Navigation />
          </body>
        </html>
      </ThemeRegistry>
    </>
  );
}
